spring.application.name=resort

# Tomcat ìë²ë¥¼ ë´ì¥ëì´ ìë¤.
# ìë í¬í¸ë²í¸ë 8080ì¸ë° => 8090ì¼ë¡ ë³ê²½í¨
# Tomcat
server.port=8090

# Dev Tools
spring.devtools.restart.enabled=true

# Thymeleaf #ì£¼ì
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/resort?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=12345678

# Mybatis
mybatis.config-location=classpath:mybatis/config/mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mappers/*.xml

# [ì¶ê°] MyBatis SQL ë¡ê·¸ ì¶ë ¥ ì¤ì 
# í¨í¤ì§ ê²½ë¡(com.green.member.mapper)ì ë¡ê·¸ ë ë²¨ì DEBUGë¡ ì¤ì íë©´ 
# ì¤íëë SQLë¬¸ê³¼ ì ë¬ëë íë¼ë¯¸í°(? ê°)ë¥¼ ì½ììì ë³¼ ì ììµëë¤.
logging.level.resort.product.mapper=DEBUG
logging.level.resort.board.mapper=DEBUG
logging.level.resort.member.mapper=DEBUG
logging.level.resort.hotel.mapper=DEBUG
logging.level.resort.mypage.mapper=DEBUG
logging.level.resort.notice.mapper=DEBUG
logging.level.resort.reservation.mapper=DEBUG
logging.level.resort.guest.mapper=DEBUG
logging.level.resort.room.mapper=DEBUG


spring.servlet.multipart.enabled=true
# íì¼ íëì ìµë ì¬ì´ì¦ (ì: 10MB)
#spring.servlet.multipart.max-file-size=10MB
# í ë²ì ìì²­(íì¼ ì¬ë¬ê° í¬í¨)ì ì ì²´ ìµë ì¬ì´ì¦ (ì: 20MB)
#spring.servlet.multipart.max-request-size=20MB

#DB와 시간오차 안나게 설정
spring.jackson.time-zone=Asia/Seoul


# 파일 크기 제한도 필요시 함께 설정
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB

#구글 OTP API
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bjoj1234@gmail.com
spring.mail.password=qairpzlpvyknhkng
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
frontend.url=http://localhost:5173
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.debug=true
